name:                assignterpreter
version:             0.1.0.0
github:              "lospollosenjoyer/assignterpreter"
license:             MIT
author:              "Bogdan Kharisov"
maintainer:          "bbh4rris@gmail.com"
copyright:           "2025 Bogdan Kharisov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            language, compilers-interpreters

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lospollosenjoyer/assignterpreter#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers

default-extensions:
  - OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - array
    - bytestring
  build-tools:
    - alex
    - happy

tests:
  assignterpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assignterpreter
    - bytestring
    - hspec
